---

- name: Install keepalived
  become: true
  ansible.builtin.package:
    name: keepalived
    state: present

- name: Deploy keepalived configuration
  become: true
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart keepalived

- name: Enable and start keepalived
  become: true
  ansible.builtin.service:
    name: keepalived
    enabled: true
    state: started
