- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts["os_family"] == 'Debian'

- name: Install base packages
  become: true
  ansible.builtin.package:
    name: "{{ base_packages }}"
    state: present
  ignore_errors: true

- name: Install extra packages per group (if defined)
  become: true
  ansible.builtin.package:
    name: "{{ extra_packages | default([]) }}"
    state: present

- name: Install fetchtool
  ansible.builtin.import_tasks: fetchtool.yml
  tags:
    - packages
    - fetchtool
    - common