deploy_versions:
  authelia:     "latest"
  gitea:        "latest-rootless"
  grafana:      "latest"
  immich:       "v2.3.1"
  nutify:       "arm64-latest"
  paperless:    "latest"
  unifi:        "latest"
  vaultwarden:  "latest"
  wikijs:       "latest"
