msmtp_:
  account: "strato"
  smtp_server: "smtp.strato.de"
  smtp_port: "587"
  smtp_user: "ondre@ondre.de"
  smtp_pass: "{{ vault_msmtp_strato_smtp_pass }}"
  start_tls: "on"
  from_address: "ganzgrosseskino@ondre.de"

  users:
    - owner: "nut"
      group: "nut"
      mode: "0600"
      dest: "/var/lib/nut/.msmtprc"
      from_address: "reaktorunfall@ondre.de"
    - owner: "root"
      group: "root"
      mode: "0600"
      dest: "/etc/msmtprc"
      from_address: "root@ondre.de"
