wireguard_role: client
wireguard_interface: wg0

wireguard_endpoint_host: "kuellenberg.eu"
wireguard_endpoint_port: 51820
wireguard_allowed_ips:
  - "10.42.0.0/24"

wireguard_persistent_keepalive: 25
