---

- name: VPS Base config
  hosts: strato_vps
  gather_facts: true
  roles:
    - role: common
      tags: ['common']
    - role: vps_base
      tags: ['vps_base']
    - role: traefik_vps
      tags: ['traefik_vps']
    - role: authelia
      tags: ['authelia']
    - role: filebrowser
      tags: ['filebrowser']
    - role: excalidraw
      tags: ['excalidraw']
